### ISSUE TITLE
Compilation error on Manjaro KDE (fatal error)

### ISSUE THREAD

**Issue by Exponent4806** [Ajatt-Tools/gd-tools#12]
GD-Tools cannot be updated in Manjaro KDE (Unstable) via "yay". The following error appears:

>[` 36%]: cache compiling.release tests/tests_main.cpp
/usr/bin/gcc -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Werror -O2 -std=c++23 -include precompiled.h -I build/.objs/tests/linux/x86_64/release/src/cxx -isystem /home/m/.xmake/packages/c/cpr/1.10.3/bdfe1ef63fba49f08efa4ef72019f9dd/include -DNDEBUG -o build/.objs/tests/linux/x86_64/release/tests/tests_main.cpp.o tests/tests_main.cpp
error: tests/tests_main.cpp:4:10: fatal error: catch2/catch.hpp: No such file or directory
    4 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: gd-tools-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
> gd-tools-git - exit status 4`

**Comment by tatsumoto-ren** [comment]
>catch2/catch.hpp: No such file or directory   

Try installing `catch2` from the official repos, then run `trizen -S gd-tools-git` again.

**Comment by Exponent4806** [comment]
Thank you ! That solved the issue!
