### ISSUE TITLE
Is `gd-tools` have a plan to support Windows10?

### ISSUE THREAD

**Issue by scillidan** [Ajatt-Tools/gd-tools#15]
Hi, guys. I want to install `gd-tools` on Windows10. But when I run `quicktest.sh`, it say:

```sh
+ readonly mode=release
+ mode=release
+ readonly prog=tests
+ prog=tests
+ xmake f -m release
checking for platform... mingw
checking for architecture... x86_64
checking for mingw directory...C:/Program Files/Git/mingw64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64)version...19.36.32537 note: the following packages are unsupported on mingw/x86_64:
	-> cpr 1.10.3
```

I tried to use `pacman` install `cpr`, the version is [1.10.5-1](https://packages.msys2.org/package/mingw-w64-clang-x86_64-cpr?repo=clang64):

```sh
msys2
pacman -Syu
pacman -S marisa-trie
pacman -S mingw-w64-x86_64-cpr
```

Or [vcpkg](https://github.com/microsoft/vcpkg), the `cpr` version is `1.10.2+3`:

```sh
vcpkg install cpr:x64-windows
```

But got the same result. 

So, did `gd-tools` only be used in Linux? 

If so, do you have any plans to support Windows 🤡 in the future ?

**Comment by tatsumoto-ren** [comment]
None of the current members of  the Ajatt-Tools organization use Windows. We don't recommend Windows because it's malicious. But if you're interested in supporting Windows, join our chat to discuss it in detail.

**Comment by scillidan** [comment]
@tatsumoto-ren Well, I have become a victim of Windows🤡, but Linux is too difficult for me. I like to use free/libre software, so it's not so bad. My ability should not be enough to support `windows-build` at present, but I'd like to join your Telegram channel to keep watching 👀.

**Comment by tatsumoto-ren** [comment]
In my experience GNU/Linux is much simpler and more user-friendly than proprietary systems. There are distros designed specifically for new users, such as Endeavor OS.

**Comment by scillidan** [comment]
@tatsumoto-ren It looks good. If I have an idle PC, I think I will try Linux from this system.
