### ISSUE TITLE
building on debian fails

### ISSUE THREAD

**Issue by darkralts** [Ajatt-Tools/gd-tools#17]
after git clone with all deps installed, running ./quickinstall.sh works but runs into error later on 

```
checking for flags (-fdiagnostics-color=always) ... ok
error: In file included from src/echo.cpp:19:
src/kana_conv.h: In function ‘constexpr auto enum_unicode_chars(std::string_view)’:
src/kana_conv.h:44:22: error: ‘enumerate’ is not a member of ‘std::views’
   44 |   return std::views::enumerate(str) //
      |                      ^~~~~~~~~
src/kana_conv.h:40:16: error: invalid return type ‘auto’ of ‘constexpr’ function ‘constexpr auto enum_unicode_chars(std::string_view)’
   40 | constexpr auto enum_unicode_chars(std::string_view str)
      |                ^~~~~~~~~~~~~~~~~~
src/kana_conv.h: In function ‘constexpr auto iter_unicode_chars(std::string_view)’:
src/kana_conv.h:53:16: error: invalid return type ‘auto’ of ‘constexpr’ function ‘constexpr auto iter_unicode_chars(std::string_view)’
   53 | constexpr auto iter_unicode_chars(std::string_view str)

```
![image](https://github.com/Ajatt-Tools/gd-tools/assets/16366107/8cff262c-142c-494c-86d3-0a469c151664)

os: debian stable

**Comment by tatsumoto-ren** [comment]
> error: ‘enumerate’ is not a member of ‘std::views’

Most likely you have an outdated compiler version, and it doesn't support some of the c++ features we use in the codebase. 

Try running:
```
gcc --version
```

For me it prints
```
gcc (GCC) 13.2.1 20230801
```

**Comment by darkralts** [comment]
ok i think it worked :) 

![image](https://github.com/Ajatt-Tools/gd-tools/assets/16366107/f73ee3a3-c26a-447b-906b-d789c18ae998)

for anyone else using debian you need to switch from `bookworm` to `trixie` which can be done by changing the word bookworm to trixie in 

/etc/apt/sources.list
`deb https://deb.debian.org/debian/ trixie main contrib `
