### ISSUE TITLE
[gd-ankisearch] Add option to display "Tags"

### ISSUE THREAD

**Issue by Exponent4806** [Ajatt-Tools/gd-tools#19]
**Problem:** "gd-ankisearch" can query the fields of cards but there seems to be no way to query the tags.

![grafik](https://github.com/Ajatt-Tools/gd-tools/assets/121114125/7ab6c991-b09a-4614-8708-dd1138b8b43f)

**Solution:** add an option to query tags and display them as a "field" on GoldenDict-ng

**Background:** In the field of Medicine, we need to use tags to properly study some topics. In a particular usage case, we need tags to know in which city some words are evaluated in a medical language exam. Without tags, we miss important information on the query.

It would be great if this new option could be implemented. Thanks for your great work!

**Comment by tatsumoto-ren** [comment]
> add an option to query tags and display them as a "field" on GoldenDict-ng

good idea.
