### ISSUE TITLE
 Notice of GPL Violation: Legal Action and Repository Takedown

### ISSUE THREAD

**Issue by KonstantinDjairo** [Ajatt-Tools/gd-tools#23]
Dear Tatsumoto,

I am writing to formally notify you of a significant violation of the GNU General Public License (GPL) within your repository, gd-tools, hosted on github. It has come to our attention that your actions have infringed upon the fork/modify and distribute freedoms granted by the GPL, resulting in significant damages to those who forked the software.

Under the GPL, users are explicitly granted the right to fork, modify, and distribute software covered by the license, provided they adhere to its terms. However, it appears that your repository has failed to comply with these essential principles, thereby violating the terms of the GPL and causing harm to individuals who have exercised their rights under the license.

Please be advised that this violation constitutes a serious breach of open-source licensing obligations and has resulted in tangible damages to those affected. As such, we are prepared to pursue legal action to seek damages for the harm caused to individuals who have forked the software from your repository.

Additionally, unless prompt action is taken to remedy the GPL violation and address the damages claimed, we will be compelled to take further measures, including the takedown of your repository from github. Failure to comply with this directive may result in legal action and the permanent removal of your repository from the platform.

We urge you to take this matter seriously and take immediate action to remedy the GPL violation within your repository. Additionally, we request that you provide compensation for the damages incurred by individuals who have been adversely affected by your actions.

Should you have any questions or require clarification regarding the steps needed to achieve compliance with the GPL or regarding the damages claimed, please do not hesitate to contact us. However, please be aware that continued non-compliance and failure to address the damages may result in legal action and repository takedown without further notice.

Thank you for your prompt attention to this matter.

Sincerely, Hashirama

**Comment by tatsumoto-ren** [comment]
Dear Konstantin. I think there's been a misunderstanding. You may fork and modify the repository as you wish. The fork button is always active. But if you do so and don't return your changes, I'm gonna tell everyone that you're a dick. I have the freedom as well. The reason is that at ajatt-tools we value working together for everyone's collective benefit. We think that forking and not returning your changes is selfish. I have already told you this in a DM.

**Comment by KonstantinDjairo** [comment]
you claim that i didn't upstreamed the changes, but it's available at codeberg
you also claim that you didn't harassed me after I've made a fork of your repository.
be careful with what you're saying, i have enough proof that you indeed have some guilty in this, and you did violated my rights as an user.

**Comment by KonstantinDjairo** [comment]
as an contributor of this project why would i suddenly stop contributing ?
you refused to give support to a wider range of systems , then I've made my fork.
but this is not the first time that you act with disrespect with people, you're well known by this hostile behavior, for some people that i won't mention.
