### ISSUE TITLE
Gd-mecab

### ISSUE THREAD

**Issue by trak43** [Ajatt-Tools/gd-tools#5]
Gd-mecab is saying 'not enough parameters' when I am copying subtitles to goldendict through mpvacious.
I have installed the corrent dependencies, installed gd-tools and sometimes mecab works however in this case it does not work.
I have configured mecab correctly and put this:
gd-mecab --word %GDWORD% --sentence %GDSENTENCE%
I get exit code 1 not enough parameters

**Comment by tatsumoto-ren** [comment]
Do you get the same exit code when running gd-mecab from the terminal? 

Change %GDSENTENCE% to %GDSEARCH%.

![screenshot-2023-04-29-00-55-14](https://user-images.githubusercontent.com/69171671/235274113-b917260a-a710-4130-935c-ea768ba173c3.png)

**Comment by trak43** [comment]
It works when I use the terminal, I used the test bash script to test it and it works.
The program works when I type it in manually however it gets stuck on that one and the input from mpvacious does not get put into mecab while it does work on the pics

**Comment by trak43** [comment]
![image](https://user-images.githubusercontent.com/132111459/235298122-7310ccb6-e6f5-4e6d-b770-057a65f0f2e7.png)
The issue still persists with %GDSEARCH%

**Comment by tatsumoto-ren** [comment]
> The issue still persists with %GDSEARCH%

Does your version of GoldenDict support `%GDSEARCH%`? It's a recently added feature.

**Comment by trak43** [comment]
So I found a work around, if I just click on the history it will show the mecab perfectly. However while if I directly send a send a sentence through mpvacious it will say there are not enough parameters and it floods my notifications. Mecab definitely works but there is a bug. 
Also I just did yay -Syu and there are no updates.
![image](https://user-images.githubusercontent.com/132111459/235301176-47452463-1d23-463c-8fbf-89caa386c102.png)

**Comment by tatsumoto-ren** [comment]
I'll test it with mpvacious. For now if you're having trouble, replace gd-mecab with gd-marisa.

**Comment by trak43** [comment]
To try and explain the current issue I have in more detail, the goldendict pop up doesn't automatically update so it's tedious since I have to go to another window, click on the history and then make a new card. Gd-pics, on the other hand, updates so I think it's a mecab specific problem.

**Comment by trak43** [comment]
It's worth mentioning that I'm using mecab-git and mecab-ipadic from archlinux-cn. mecab-ipadic-git from the aur recently stopped installing and I confirmed this is not an aur manager problem as I tried installing it manually. They're both the same program though so this probably isn't the issue but it's worth testing if you don't find anything.

**Comment by tatsumoto-ren** [comment]
I can't reproduce this behavior on my machine (with mpvacious or without). But I also have `mecab-git` from `archlinuxcn`.

**Comment by void8192** [comment]
> I'll test it with mpvacious. For now if you're having trouble, replace gd-mecab with gd-marisa.

gd-marisa also does not work in goldendict secondary windows. I'm using `mecab-git` from AUR and `marisa` from arch official repo
![image](https://github.com/Ajatt-Tools/gd-tools/assets/45062062/101fecbb-da35-4bb8-85b8-1637a0cf0439)

Goldendict-ng 23.07.25.e44a259e at 2023-08-17T16:40:03
Qt 6.5.2 GCC 13.2.1 20230801 arch linux 6.4.10-zen2-1-zen x86_64-little_endian-lp64
Flags:USE_XAPIAN MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

**Comment by void8192** [comment]
I checked and found out that there is something wrong with %GDSEARCH% passed from goldendict

**Comment by tatsumoto-ren** [comment]
> I checked and found out that there is something wrong with %GDSEARCH% passed from goldendict

Did you pass wrong arguments? If so, make sure that %GDSEARCH% is preceded by `--sentence`. For example, `gd-marisa --word %GDWORD% --sentence %GDSEARCH%`

**Comment by void8192** [comment]
> > I checked and found out that there is something wrong with %GDSEARCH% passed from goldendict
> 
> Did you pass wrong arguments? If so, make sure that %GDSEARCH% is preceded by `--sentence`. For example, `gd-marisa --word %GDWORD% --sentence %GDSEARCH%`

I think this is a bug of the new version of Goldendict. Everything works in the main window, but as soon as I open the secondary window (e.g. scanner), %GDSEARCH% is passed empty

**Comment by void8192** [comment]
@trak43, another way to fix:
![image](https://github.com/Ajatt-Tools/gd-tools/assets/45062062/3194aa83-4593-4672-8404-6863246ce2b1)
