### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by phudang-135** [Ajatt-Tools/gd-tools#7]
Hi, 

I run `make install` and has this error:

`install -Dm755 gd-ankisearch/gd-ankisearch.sh /usr/bin/gd-ankisearch
process_begin: CreateProcess(NULL, install -Dm755 gd-ankisearch/gd-ankisearch.sh /usr/bin/gd-ankisearch, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:29: /usr/bin/gd-ankisearch] Error 2`

From what I understand, it is looking for /usr/bin/gd-ankisearch?

**Comment by tatsumoto-ren** [comment]
Did you run `make` before running `make install`?

**Comment by phudang-135** [comment]
> Did you run `make` before running `make install`?

Hi, I just run `make` and the following error show up:

`-e '\033[1;32mBuilding the program...\033[0m'
mkdir -p build
g++ gd-marisa/gd-marisa.cpp -lmarisa -o build/gd-marisa
process_begin: CreateProcess(NULL, g++ gd-marisa/gd-marisa.cpp -lmarisa -o build/gd-marisa, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:23: build/gd-marisa] Error 2`

It look like it did not see marisa. However, I did install goldendict on my using the provided .exe file. Do I need to install marisa separately? 

Edit: I am using windows, maybe that is the problem? I suppose the tools are not written for Windows?

**Comment by tatsumoto-ren** [comment]
>  Do I need to install marisa separately?

If it isn't installed, install the `marisa` package. https://archlinux.org/packages/extra/x86_64/marisa/

**Comment by phudang-135** [comment]
Hi,

I have decided to just install Arch Linux and went from there. Everything works now. Thank you for your time.

**Comment by tatsumoto-ren** [comment]
Awesome!
